version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: keycloak_postgres
    environment:
      POSTGRES_DB: ${KC_POSTGRES_DB}
      POSTGRES_USER: ${KC_POSTGRES_USER} 
      POSTGRES_PASSWORD: ${KC_POSTGRES_PASSWORD} 
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - keycloak_network

  keycloak:
    image: quay.io/keycloak/keycloak:21.1.1
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: ${KC_POSTGRES_DB}
      KC_DB_URL_HOST: postgres
      KC_DB_USERNAME: ${KC_POSTGRES_USER} 
      KC_DB_PASSWORD: ${KC_POSTGRES_PASSWORD} 
      KC_HEALTH_ENABLED: "true"
      KC_METRICS_ENABLED: "true"
    command: start-dev --import-realm
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    volumes:
      - keycloak_data:/opt/keycloak/data
      - ./keycloak/realms:/opt/keycloak/data/import
    networks:
      - keycloak_network
  
  weather-web-app:
    build:
      context: ./WeatherWebApp
      dockerfile: dockerfile
    container_name: weather-web-app
    ports:
      - "5278:8080"
    networks:
      - keycloak_network

  weather-web-app-client:
    build:
      context: ./WeatherWebAppClient
      dockerfile: dockerfile
    container_name: weather-web-app-client
    ports:
      - "44456:80"
    networks:
      - keycloak_network

volumes:
  postgres_data:
  keycloak_data:

networks:
  keycloak_network:
    driver: bridge